# berlin netplan

network:
  ethernets:
    ens3:
      addresses:
      - 192.168.122.100/24 
      #gateway4: 192.168.122.1
    ens4:
      addresses:
      - 10.102.1.2/29
      - 2001:db8:1:2::2/125
      routes:
        - to: 0.0.0.0/0
          via: 10.102.1.3
          metric: 100
        - to: 10.102.1.0/24
          via: 10.102.1.1
        - to: fc00:0::/32
          via: 2001:db8:1:2::1
      nameservers:
        addresses:
        - 8.8.8.8
        search:
        - demo.dcloud.cisco.com
    ens5:
      addresses:
      - 10.102.1.17/31
      - 2001:db8:1:2::17/127
      routes:
        - to: 10.102.1.0/24
          via: 10.102.1.16
        - to: fc00:0::/32
          via: 2001:db8:1:2::16
  version: 2