# berlin netplan

network:
  ethernets:
    ens3:
      addresses:
      - 192.168.122.100/24 
      gateway4: 192.168.122.1

    ens4:
      addresses:
      - 10.1.2.1/31
      - 2001:1:1:1::1/127
      routes:
        - to: 0.0.0.0/0
          via: 198.18.4.3
          metric: 100
        - to: 198.18.5.0/24
          via: 198.18.4.1
        - to: fc00:0::/32
          via: fc00:0:8888::1
      nameservers:
        addresses:
        - 8.8.8.8
        search:
        - demo.dcloud.cisco.com
    ens5:
      addresses:
      - 198.18.5.1/24
      - fc00:0:9999::1/64
      routes:
        - to: 0.0.0.0/0
          via: 198.18.5.2
        - to: 198.18.4.0/24
          via: 198.18.5.2
  version: 2