- name: validate SONiC local srv6 SIDs
  hosts: sonic
  become: true
  tasks:

    - name: check srv6 SIDs
      shell: "ip -6 route show | grep -e seg6 -e fe00"
      register: srv6_sid_result

    - name: print srv6 SIDs
      debug:
        var: srv6_sid_result.stdout