---

# ansible-playbook -i hosts trex-playbook.yaml -e "ansible_user=cisco ansible_ssh_pass=cisco123 ansible_sudo_pass=cisco123" -vv

- name: Apply config_db.json and frr.conf to SONiC routers
  hosts: localhost
  become: true
  tasks:

    - name: run trex docker exec script
      command: "scripts/host-routes.sh"
      ignore_errors: yes
   