network:
  ethernets:
    eth0:
      addresses:
      - 10.254.254.108/24
      gateway4: 10.254.254.1
      nameservers:
        addresses:
        - 8.8.8.8

    eth1:
      addresses:
        - 10.101.1.2/24
        - fc00:0:101:1::2/64
      routes:
        - to: 10.0.0.0/24
          via: 10.101.1.1
        - to: 10.107.1.0/24
          via: 10.101.1.1
        - to: 10.1.1.0/24
          via: 10.101.1.1
        - to: fc00:0::/32
          via: fc00:0:101:1::1

    eth2:
      addresses:
        - 10.101.2.2/24
        - fc00:0:101:2::2/64
      routes:
        - to: 10.107.2.0/24
          via: 10.101.2.1
        - to: fc00:0:107:2::/64
          via: fc00:0:101:2::1

  version: 2