---

# ansible-playbook -i ansible/hosts ansible/deploy-playbook.yaml -e "ansible_user=cisco ansible_ssh_pass=cisco123 ansible_sudo_pass=cisco123" -vv

- name: Add bridges and deploy clab topology
  hosts: localhost
  become: true
  tasks:

    - name: deploy clab topology
      command: "clab deploy -t ../lab_4-topology.clab.yaml"
      ignore_errors: yes

    - name: ssh-keygen
      command: "scripts/ssh-keygen.sh"
      ignore_errors: yes
