network:
  ethernets:
    eth0:
      addresses:
      - 10.254.254.109/24
      gateway4: 10.254.254.1
      nameservers:
        addresses:
        - 8.8.8.8

    eth1:
      addresses:
        - 10.107.1.2/24
        - fc00:0:107:1::2/64
      routes:
        - to: 10.0.0.0/24
          via: 10.107.1.1
        - to: 10.101.1.0/24
          via: 10.107.1.1
        - to: 10.1.1.0/24
          via: 10.107.1.2
        - to: fc00:0::/32
          via: fc00:0:107:1::1

    eth2:
      addresses:
        - 10.107.2.2/24
        - fc00:0:107:2::2/64
      routes:
        - to: 10.101.2.0/24
          via: 10.107.2.1
        - to: 10.200.0.0/24
          via: 10.107.2.1
        - to: fc00:0:101:2::/64
          via: fc00:0:107:2::1
    lo:
       addresses:
        - 20.0.0.1/24
        - 30.0.0.1/24
        - 40.0.0.1/24
        - 50.0.0.1/24
        - fc00:0:40::1/64
        - fc00:0:50::1/64

  version: 2