# ansible-playbook -e "ansible_user=dcloud ansible_ssh_pass=C1sco12345 ansible_sudo_pass=C1sco12345" /home/dcloud/LTRMSI-3000/ansible/dcloud_startup_playbook.yaml -vv

- name: Update the Git Repo
  hosts: localhost
  become: false
  tasks:

    - name: git pull to update repo on localhost
      command: git pull
      args:
        chdir: /home/cisco/LTRMSI-3000
      ignore_errors: yes

- name: Berlin VM
  hosts: localhost
  become: true
  tasks:

    - name: define virsh network
      command: virsh net-define ../lab_1/config/berlin-vm/berlin-net.xml
      ignore_errors: yes

    - name: start virsh network
      command: virsh net-start berlin-net
      ignore_errors: yes

    - name: add berlin-net bridge
      command: brctl addbr berlin-net
      ignore_errors: yes

    - name: berlin-net link up
      command: ip link set berlin-net up
      ignore_errors: yes

    - name: berlin-net ip address
      command: ip addr add 198.18.4.3/24 dev berlin-net
      ignore_errors: yes

    - name: berlin-net masquerade
      command: iptables -t nat -A POSTROUTING -o ens160 -j MASQUERADE 
      ignore_errors: yes

    - name: define virsh domain
      command: virsh define ../lab_1/config/berlin-vm/berlin.xml
      ignore_errors: yes

    - name: start Berlin VM
      command: virsh start berlin
      ignore_errors: yes





